//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetailInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public System.DateTime Date { get; set; }
        public long OrderId { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal RefundTotalAmount { get; set; }
        public decimal RefundCommisAmount { get; set; }
        public AccountDetailInfo.EnumOrderType OrderType { get; set; }
        public decimal FreightAmount { get; set; }
        public decimal ProductActualPaidAmount { get; set; }
        public long AccountId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderRefundsDates { get; set; }
        public decimal BrokerageAmount { get; set; }
        public decimal ReturnBrokerageAmount { get; set; }
        public System.DateTime OrderFinshDate { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal SettlementAmount { get; set; }
        public string ShopName { get; set; }
        public string PaymentTypeName { get; set; }
    
        public virtual AccountInfo Himall_Accounts { get; set; }

        /// <summary>
        /// 开团奖励
        /// </summary>
        public decimal OpenCommission { get; set; }
        /// <summary>
        /// 每单返现
        /// </summary>
        public decimal JoinCommission { get; set; }
    }
}
