//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPurchaseAgreementInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> AccountId { get; set; }
        public long ShopId { get; set; }
        public System.DateTime Date { get; set; }
        public long PurchaseAgreementId { get; set; }
        public decimal AdvancePayment { get; set; }
        public System.DateTime FinishDate { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual AccountInfo Himall_Accounts { get; set; }
    }
}
