//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyWithDrawInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long MemId { get; set; }
        public string NickName { get; set; }
        public string OpenId { get; set; }
        public Model.ApplyWithDrawInfo.ApplyWithDrawStatus ApplyStatus { get; set; }
        public decimal ApplyAmount { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string PayNo { get; set; }
        public string OpUser { get; set; }
        public string Remark { get; set; }
    }
}
