//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMessagesInfo:BaseModel
    {
        int _id;
        public new int Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> ShopBranchId { get; set; }
        public Nullable<long> ShopId { get; set; }
        public int TypeId { get; set; }
        public long SourceId { get; set; }
        public string Content { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime sendtime { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> OrderPayDate { get; set; }
    }
}
