//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long CategoryId { get; set; }
        public string Title { get; set; }
        public string IconUrl { get; set; }
        public string Content { get; set; }
        public System.DateTime AddDate { get; set; }
        public long DisplaySequence { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public bool IsRelease { get; set; }
    
        public virtual ArticleCategoryInfo ArticleCategoryInfo { get; set; }
    }
}
