//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusInfo:BaseModel
    {
        public BonusInfo()
        {
            this.Himall_BonusReceive = new HashSet<BonusReceiveInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Model.BonusInfo.BonusType Type { get; set; }
        public Model.BonusInfo.BonusStyle Style { get; set; }
        public string Name { get; set; }
        public string MerchantsName { get; set; }
        public string Remark { get; set; }
        public string Blessing { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string QRPath { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public Nullable<decimal> RandomAmountStart { get; set; }
        public Nullable<decimal> RandomAmountEnd { get; set; }
        public int ReceiveCount { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public bool IsInvalid { get; set; }
        public Nullable<Model.BonusInfo.BonusPriceType> PriceType { get; set; }
        public decimal ReceivePrice { get; set; }
        public string ReceiveHref { get; set; }
        public bool IsAttention { get; set; }
        public bool IsGuideShare { get; set; }
    
        public virtual ICollection<BonusReceiveInfo> Himall_BonusReceive { get; set; }
    }
}
