//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandInfo:BaseModel
    {
        public BrandInfo()
        {
            this.TypeBrandInfo = new HashSet<TypeBrandInfo>();
            this.FloorBrandInfo = new HashSet<FloorBrandInfo>();
            this.Himall_ShopBrands = new HashSet<ShopBrandsInfo>();
            this.Himall_ShopBrandApplys = new HashSet<ShopBrandApplysInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string Name { get; set; }
        public long DisplaySequence { get; set; }
        private string logo { get; set; }
        public string RewriteName { get; set; }
        public string Description { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public bool IsRecommend { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<TypeBrandInfo> TypeBrandInfo { get; set; }
        public virtual ICollection<FloorBrandInfo> FloorBrandInfo { get; set; }
        public virtual ICollection<ShopBrandsInfo> Himall_ShopBrands { get; set; }
        public virtual ICollection<ShopBrandApplysInfo> Himall_ShopBrandApplys { get; set; }
    }
}
