//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerageRefundInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> IncomeId { get; set; }
        public decimal Brokerage { get; set; }
        public Nullable<System.DateTime> RefundTime { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public long RefundId { get; set; }
    
        public virtual BrokerageIncomeInfo Himall_BrokerageIncome { get; set; }
    }
}
