//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerageIncomeInfo:BaseModel
    {
        public BrokerageIncomeInfo()
        {
            this.Himall_BrokerageRefund = new HashSet<BrokerageRefundInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> OrderItemId { get; set; }
        public string SkuID { get; set; }
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string SkuInfo { get; set; }
        public decimal Brokerage { get; set; }
        public Nullable<long> ShopId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public long BuyerUserId { get; set; }
        public BrokerageIncomeInfo.BrokerageStatus Status { get; set; }
        public Nullable<System.DateTime> SettlementTime { get; set; }
        public long UserId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public System.DateTime OrderTime { get; set; }
    
        public virtual ICollection<BrokerageRefundInfo> Himall_BrokerageRefund { get; set; }
    }
}
