//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCategoriesApplyInfo:BaseModel
    {
        public BusinessCategoriesApplyInfo()
        {
            this.Himall_BusinessCategoriesApplyDetail = new HashSet<BusinessCategoriesApplyDetailInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public System.DateTime ApplyDate { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public Himall.Model.BusinessCategoriesApplyInfo.BusinessCateApplyStatus AuditedStatus { get; set; }
        public Nullable<System.DateTime> AuditedDate { get; set; }
    
        public virtual ICollection<BusinessCategoriesApplyDetailInfo> Himall_BusinessCategoriesApplyDetail { get; set; }
    }
}
