//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashDepositDetailInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long CashDepositId { get; set; }
        public System.DateTime AddDate { get; set; }
        public decimal Balance { get; set; }
        public string Operator { get; set; }
        public string Description { get; set; }
        public Nullable<int> RechargeWay { get; set; }
    
        public virtual CashDepositInfo Himall_CashDeposit { get; set; }
    }
}
