//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashDepositInfo:BaseModel
    {
        public CashDepositInfo()
        {
            this.Himall_CashDepositDetail = new HashSet<CashDepositDetailInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal TotalBalance { get; set; }
        public System.DateTime Date { get; set; }
        public bool EnableLabels { get; set; }
    
        public virtual ICollection<CashDepositDetailInfo> Himall_CashDepositDetail { get; set; }
        public virtual ShopInfo Himall_Shops { get; set; }
    }
}
