//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryInfo:BaseModel
    {
        public CategoryInfo()
        {
            this.FloorCategoryInfo = new HashSet<FloorCategoryInfo>();
            this.HomeCategoryInfo = new HashSet<HomeCategoryInfo>();
            this.BusinessCategoryInfo = new HashSet<BusinessCategoryInfo>();
            this.Himall_Products = new HashSet<ProductInfo>();
            this.Himall_BusinessCategoriesApplyDetail = new HashSet<BusinessCategoriesApplyDetailInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string Name { get; set; }
        public string Icon { get; set; }
        public long DisplaySequence { get; set; }
        public long ParentCategoryId { get; set; }
        public int Depth { get; set; }
        public string Path { get; set; }
        public string RewriteName { get; set; }
        public bool HasChildren { get; set; }
        public long TypeId { get; set; }
        public decimal CommisRate { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Description { get; set; }
        public string Meta_Keywords { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ProductTypeInfo ProductTypeInfo { get; set; }
        public virtual ICollection<FloorCategoryInfo> FloorCategoryInfo { get; set; }
        public virtual ICollection<HomeCategoryInfo> HomeCategoryInfo { get; set; }
        public virtual ICollection<BusinessCategoryInfo> BusinessCategoryInfo { get; set; }
        public virtual ICollection<ProductInfo> Himall_Products { get; set; }
        public virtual CategoryCashDepositInfo Himall_CategoryCashDeposit { get; set; }
        public virtual ICollection<BusinessCategoriesApplyDetailInfo> Himall_BusinessCategoriesApplyDetail { get; set; }
    }
}
