//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollocationPoruductInfo:BaseModel
    {
        public CollocationPoruductInfo()
        {
            this.Himall_CollocationSkus = new HashSet<CollocationSkuInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ProductId { get; set; }
        public long ColloId { get; set; }
        public bool IsMain { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
    
        public virtual CollocationInfo Himall_Collocation { get; set; }
        public virtual ICollection<CollocationSkuInfo> Himall_CollocationSkus { get; set; }
        public virtual ProductInfo Himall_Products { get; set; }
    }
}
