//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponSendByRegisterInfo:BaseModel
    {
        public CouponSendByRegisterInfo()
        {
            this.Himall_CouponSendByRegisterDetailed = new HashSet<CouponSendByRegisterDetailedInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Himall.CommonModel.CouponSendByRegisterStatus Status { get; set; }
        public string Link { get; set; }
    
        public virtual ICollection<CouponSendByRegisterDetailedInfo> Himall_CouponSendByRegisterDetailed { get; set; }
    }
}
