//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServiceInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public CustomerServiceInfo.ServiceTool Tool { get; set; }
        public CustomerServiceInfo.ServiceType Type { get; set; }
        public string Name { get; set; }
        public string AccountCode { get; set; }
        public Model.CustomerServiceInfo.ServiceTerminalType TerminalType { get; set; }
        public Model.CustomerServiceInfo.ServiceStatusType ServerStatus { get; set; }
    }
}
