//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionShareSetting:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string ProShareLogo { get; set; }
        public string ShopShareLogo { get; set; }
        public string ProShareTitle { get; set; }
        public string ShopShareTitle { get; set; }
        public string ProShareDesc { get; set; }
        public string ShopShareDesc { get; set; }
        public string DisShareLogo { get; set; }
        public string RecruitShareLogo { get; set; }
        public string DisShareTitle { get; set; }
        public string RecruitShareTitle { get; set; }
        public string DisShareDesc { get; set; }
        public string RecruitShareDesc { get; set; }
    }
}
