//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FightGroupOrderInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> ActiveId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<bool> IsFirstOrder { get; set; }
        public Nullable<System.DateTime> JoinTime { get; set; }
        public Nullable<int> JoinStatus { get; set; }
        public Nullable<System.DateTime> OverTime { get; set; }
        public Nullable<long> OrderUserId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string SkuId { get; set; }
        public long Quantity { get; set; }
        public decimal SalePrice { get; set; }
        public long InvitationUserId { get; set; }
        public long ShopId { get; set; }
    }
}
