//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FightGroupsInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> HeadUserId { get; set; }
        public Nullable<long> ActiveId { get; set; }
        public Nullable<int> LimitedNumber { get; set; }
        public Nullable<decimal> LimitedHour { get; set; }
        public Nullable<int> JoinedNumber { get; set; }
        public Nullable<bool> IsException { get; set; }
        public Nullable<int> GroupStatus { get; set; }
        public Nullable<System.DateTime> AddGroupTime { get; set; }
        public Nullable<System.DateTime> OverTime { get; set; }
        public long ProductId { get; set; }
        public long ShopId { get; set; }
    }
}
