//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashSaleInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string Title { get; set; }
        public long ShopId { get; set; }
        public long ProductId { get; set; }
        public Himall.Model.FlashSaleInfo.FlashSaleStatus Status { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int LimitCountOfThePeople { get; set; }
        public int SaleCount { get; set; }
        public string CategoryName { get; set; }
        public string ImagePath { get; set; }
        public decimal MinPrice { get; set; }
    
        public virtual ProductInfo Himall_Products { get; set; }
        public virtual ShopInfo Himall_Shops { get; set; }
        public virtual ShopInfo Himall_Shops1 { get; set; }
    }
}
