//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightTemplateInfo:BaseModel
    {
        public FreightTemplateInfo()
        {
            this.Himall_FreightAreaContent = new HashSet<FreightAreaContentInfo>();
            this.Himall_Products = new HashSet<ProductInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string Name { get; set; }
        public Nullable<int> SourceAddress { get; set; }
        public string SendTime { get; set; }
        public Himall.CommonModel.FreightTemplateType IsFree { get; set; }
        public Himall.CommonModel.ValuationMethodType ValuationMethod { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public long ShopID { get; set; }
    
        public virtual ICollection<FreightAreaContentInfo> Himall_FreightAreaContent { get; set; }
        public virtual ICollection<ProductInfo> Himall_Products { get; set; }
    }
}
