//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightAreaContentInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long FreightTemplateId { get; set; }
        public string AreaContent { get; set; }
        public Nullable<int> FirstUnit { get; set; }
        public Nullable<float> FirstUnitMonry { get; set; }
        public Nullable<int> AccumulationUnit { get; set; }
        public Nullable<float> AccumulationUnitMoney { get; set; }
        public Nullable<sbyte> IsDefault { get; set; }
    
        public virtual FreightTemplateInfo Himall_FreightTemplate { get; set; }
    }
}
