//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string GiftName { get; set; }
        public int NeedIntegral { get; set; }
        public int LimtQuantity { get; set; }
        public int StockQuantity { get; set; }
        public System.DateTime EndDate { get; set; }
        public int NeedGrade { get; set; }
        public int VirtualSales { get; set; }
        public int RealSales { get; set; }
        public Model.GiftInfo.GiftSalesStatus SalesStatus { get; set; }
        public string ImagePath { get; set; }
        public int Sequence { get; set; }
        public Nullable<decimal> GiftValue { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
