//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftOrderItemInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> OrderId { get; set; }
        public long GiftId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> SaleIntegral { get; set; }
        public string GiftName { get; set; }
        public Nullable<decimal> GiftValue { get; set; }
        public string ImagePath { get; set; }
    
        public virtual GiftOrderInfo Himall_GiftsOrder { get; set; }
    }
}
