//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeFloorInfo:BaseModel
    {
        public HomeFloorInfo()
        {
            this.FloorBrandInfo = new HashSet<FloorBrandInfo>();
            this.FloorCategoryInfo = new HashSet<FloorCategoryInfo>();
            this.FloorProductInfo = new HashSet<FloorProductInfo>();
            this.FloorTopicInfo = new HashSet<FloorTopicInfo>();
            this.Himall_FloorTabls = new HashSet<FloorTablsInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string FloorName { get; set; }
        public long DisplaySequence { get; set; }
        public bool IsShow { get; set; }
        public string SubName { get; set; }
        public long StyleLevel { get; set; }
        public string DefaultTabName { get; set; }
    
        public virtual ICollection<FloorBrandInfo> FloorBrandInfo { get; set; }
        public virtual ICollection<FloorCategoryInfo> FloorCategoryInfo { get; set; }
        public virtual ICollection<FloorProductInfo> FloorProductInfo { get; set; }
        public virtual ICollection<FloorTopicInfo> FloorTopicInfo { get; set; }
        public virtual ICollection<FloorTablsInfo> Himall_FloorTabls { get; set; }
    }
}
