//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRefundInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long OrderId { get; set; }
        public long OrderItemId { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public long UserId { get; set; }
        public string Applicant { get; set; }
        public string Reason { get; set; }
        public string ContactPerson { get; set; }
        public string ContactCellPhone { get; set; }
        public string RefundAccount { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public decimal Amount { get; set; }
        public OrderRefundInfo.OrderRefundAuditStatus SellerAuditStatus { get; set; }
        public System.DateTime SellerAuditDate { get; set; }
        public string SellerRemark { get; set; }
        public OrderRefundInfo.OrderRefundConfirmStatus ManagerConfirmStatus { get; set; }
        public System.DateTime ManagerConfirmDate { get; set; }
        public string ManagerRemark { get; set; }
        public bool IsReturn { get; set; }
        public string ExpressCompanyName { get; set; }
        public string ShipOrderNumber { get; set; }
        public string Payee { get; set; }
        public string PayeeAccount { get; set; }
        public OrderRefundInfo.OrderRefundMode RefundMode { get; set; }
        public Nullable<System.DateTime> BuyerDeliverDate { get; set; }
        public Nullable<System.DateTime> SellerConfirmArrivalDate { get; set; }
        public Nullable<Model.OrderRefundInfo.OrderRefundPayStatus> RefundPayStatus { get; set; }
        public Nullable<Model.OrderRefundInfo.OrderRefundPayType> RefundPayType { get; set; }
        public string RefundBatchNo { get; set; }
        public Nullable<System.DateTime> RefundPostTime { get; set; }
        public Nullable<long> ReturnQuantity { get; set; }
        public decimal ReturnBrokerage { get; set; }
        public Nullable<int> ApplyNumber { get; set; }
        public string CertPic1 { get; set; }
        public string CertPic2 { get; set; }
        public string CertPic3 { get; set; }
        public decimal ReturnPlatCommission { get; set; }
        public string ReasonDetail { get; set; }
    
        public virtual OrderItemInfo OrderItemInfo { get; set; }
    }
}
