//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OrderInfo : BaseModel
    {
        public OrderInfo()
        {
            this.OrderComplaintInfo = new HashSet<OrderComplaintInfo>();
            this.OrderItemInfo = new HashSet<OrderItemInfo>();
            this.OrderOperationLogInfo = new HashSet<OrderOperationLogInfo>();
            this.OrderCommentInfo = new HashSet<OrderCommentInfo>();
        }

        long _id;
        public new long Id { get { return _id; } set { _id = value; base.Id = value; } }
        public OrderInfo.OrderOperateStatus OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CloseReason { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public string SellerPhone { get; set; }
        public string SellerAddress { get; set; }
        public string SellerRemark { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string UserRemark { get; set; }
        public string ShipTo { get; set; }
        public string CellPhone { get; set; }
        public int TopRegionId { get; set; }
        public int RegionId { get; set; }
        public string RegionFullName { get; set; }
        public string Address { get; set; }
        public string ExpressCompanyName { get; set; }
        public decimal Freight { get; set; }
        public string ShipOrderNumber { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public bool IsPrinted { get; set; }
        public string PaymentTypeName { get; set; }
        public string PaymentTypeGateway { get; set; }
        public string GatewayOrderId { get; set; }
        public string PayRemark { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string InvoiceTitle { get; set; }
        public decimal Tax { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public decimal ProductTotalAmount { get; set; }
        public decimal RefundTotalAmount { get; set; }
        public decimal CommisTotalAmount { get; set; }
        public decimal RefundCommisAmount { get; set; }
        public OrderInfo.ActiveTypes ActiveType { get; set; }
        public Himall.Core.PlatformType Platform { get; set; }
        public decimal DiscountAmount { get; set; }
        public InvoiceType InvoiceType { get; set; }
        public decimal IntegralDiscount { get; set; }
        public string InvoiceContext { get; set; }
        public Nullable<Himall.Model.OrderInfo.OrderTypes> OrderType { get; set; }
        public Himall.Model.OrderInfo.PaymentTypes PaymentType { get; set; }
        public Nullable<long> ShareUserId { get; set; }
        public string OrderRemarks { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public Himall.CommonModel.Enum.DeliveryType DeliveryType { get; set; }
        public Nullable<long> ShopBranchId { get; set; }
        public string PickupCode { get; set; }
        public Nullable<int> SellerRemarkFlag { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal ActualPayAmount { get; set; }
        public decimal FullDiscount { get; set; }
        public string PayCode { get; set; }
        public virtual ICollection<OrderComplaintInfo> OrderComplaintInfo { get; set; }
        public virtual ICollection<OrderItemInfo> OrderItemInfo { get; set; }
        public virtual ICollection<OrderOperationLogInfo> OrderOperationLogInfo { get; set; }
        public virtual ICollection<OrderCommentInfo> OrderCommentInfo { get; set; }
    }
}
