//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingSettlementOrdersInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public long OrderId { get; set; }
        public decimal ProductsAmount { get; set; }
        public decimal FreightAmount { get; set; }
        public decimal PlatCommission { get; set; }
        public decimal DistributorCommission { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal PlatCommissionReturn { get; set; }
        public decimal DistributorCommissionReturn { get; set; }
        public decimal SettlementAmount { get; set; }
        public System.DateTime OrderFinshTime { get; set; }
        public string ShopName { get; set; }
        public decimal OrderAmount { get; set; }
        public string PaymentTypeName { get; set; }
        /// <summary>
        /// 开团奖励
        /// </summary>
        public decimal OpenCommission { get; set; }
        /// <summary>
        /// 每单返现
        /// </summary>
        public decimal JoinCommission { get; set; }
    }
}
