//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCommentInfo:BaseModel
    {
        public ProductCommentInfo()
        {
            this.Himall_ProductCommentsImages = new HashSet<ProductCommentsImagesInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ProductId { get; set; }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string ReviewContent { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public int ReviewMark { get; set; }
        public Nullable<long> SubOrderId { get; set; }
        public string AppendContent { get; set; }
        public Nullable<System.DateTime> AppendDate { get; set; }
        public string ReplyAppendContent { get; set; }
        public Nullable<System.DateTime> ReplyAppendDate { get; set; }
        public Nullable<bool> IsHidden { get; set; }
    
        public virtual ProductInfo ProductInfo { get; set; }
        public virtual UserMemberInfo Himall_Members { get; set; }
        public virtual OrderItemInfo Himall_OrderItems { get; set; }
        public virtual ICollection<ProductCommentsImagesInfo> Himall_ProductCommentsImages { get; set; }
        public virtual ShopInfo Himall_Shops { get; set; }
    }
}
