//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBrokerageInfo:BaseModel
    {
        public ProductBrokerageInfo()
        {
            this.Himall_DistributionProducts = new HashSet<DistributionProductsInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> ProductId { get; set; }
        public decimal rate { get; set; }
        public Nullable<long> ShopId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> SaleNum { get; set; }
        public Nullable<int> AgentNum { get; set; }
        public Nullable<int> ForwardNum { get; set; }
        public ProductBrokerageInfo.ProductBrokerageStatus Status { get; set; }
        public Nullable<int> Sort { get; set; }
        public decimal saleAmount { get; set; }
        public decimal BrokerageAmount { get; set; }
        public decimal BrokerageTotal { get; set; }
    
        public virtual ProductInfo Himall_Products { get; set; }
        public virtual ShopInfo Himall_Shops { get; set; }
        public virtual ICollection<DistributionProductsInfo> Himall_DistributionProducts { get; set; }
    }
}
