//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMessageRecordInfo:BaseModel
    {
        public SendMessageRecordInfo()
        {
            this.Himall_SendmessagerecordCoupon = new HashSet<SendmessagerecordCouponInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Himall.CommonModel.MsgType MessageType { get; set; }
        public Himall.CommonModel.WXMsgType ContentType { get; set; }
        public string SendContent { get; set; }
        public string ToUserLabel { get; set; }
        public Nullable<int> SendState { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
    
        public virtual ICollection<SendmessagerecordCouponInfo> Himall_SendmessagerecordCoupon { get; set; }
    }
}
