//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettledInfo:BaseModel
    {
        public long ID { get; set; }
        public Himall.CommonModel.BusinessType BusinessType { get; set; }
        public Himall.CommonModel.SettleAccountsType SettlementAccountType { get; set; }
        public int TrialDays { get; set; }
        public Himall.CommonModel.VerificationStatus IsCity { get; set; }
        public Himall.CommonModel.VerificationStatus IsPeopleNumber { get; set; }
        public Himall.CommonModel.VerificationStatus IsAddress { get; set; }
        public Himall.CommonModel.VerificationStatus IsBusinessLicenseCode { get; set; }
        public Himall.CommonModel.VerificationStatus IsBusinessScope { get; set; }
        public Himall.CommonModel.VerificationStatus IsBusinessLicense { get; set; }
        public Himall.CommonModel.VerificationStatus IsAgencyCode { get; set; }
        public Himall.CommonModel.VerificationStatus IsAgencyCodeLicense { get; set; }
        public Himall.CommonModel.VerificationStatus IsTaxpayerToProve { get; set; }
        public Himall.CommonModel.VerificationType CompanyVerificationType { get; set; }
        public Himall.CommonModel.VerificationStatus IsSName { get; set; }
        public Himall.CommonModel.VerificationStatus IsSCity { get; set; }
        public Himall.CommonModel.VerificationStatus IsSAddress { get; set; }
        public Himall.CommonModel.VerificationStatus IsSIDCard { get; set; }
        public Himall.CommonModel.VerificationStatus IsSIdCardUrl { get; set; }
        public Himall.CommonModel.VerificationType SelfVerificationType { get; set; }
    }
}
