//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopHomeModuleInfo:BaseModel
    {
        public ShopHomeModuleInfo()
        {
            this.ShopHomeModuleProductInfo = new HashSet<ShopHomeModuleProductInfo>();
            this.Himall_ShopHomeModulesTopImg = new HashSet<ShopHomeModulesTopImgInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public string Name { get; set; }
        public bool IsEnable { get; set; }
        public int DisplaySequence { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<ShopHomeModuleProductInfo> ShopHomeModuleProductInfo { get; set; }
        public virtual ICollection<ShopHomeModulesTopImgInfo> Himall_ShopHomeModulesTopImg { get; set; }
    }
}
