//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopAccountInfo:BaseModel
    {
        public ShopAccountInfo()
        {
            this.Himall_ShopAccountItem = new HashSet<ShopAccountItemInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public string ShopName { get; set; }
        public decimal Balance { get; set; }
        public decimal PendingSettlement { get; set; }
        public decimal Settled { get; set; }
    
        public virtual ICollection<ShopAccountItemInfo> Himall_ShopAccountItem { get; set; }
    }
}
