//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopBonusReceiveInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long BonusGrantId { get; set; }
        public string OpenId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Model.ShopBonusReceiveInfo.ReceiveState State { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> UsedOrderId { get; set; }
        public string WXName { get; set; }
        public string WXHead { get; set; }
    
        public virtual UserMemberInfo Himall_Members { get; set; }
        public virtual ShopBonusGrantInfo Himall_ShopBonusGrant { get; set; }
    }
}
