//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopBrandApplysInfo:BaseModel
    {
        int _id;
        public new int Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public Nullable<long> BrandId { get; set; }
        public string BrandName { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public string AuthCertificate { get; set; }
        public int ApplyMode { get; set; }
        public string Remark { get; set; }
        public int AuditStatus { get; set; }
        public System.DateTime ApplyTime { get; set; }
    
        public virtual BrandInfo Himall_Brands { get; set; }
        public virtual ShopInfo Himall_Shops { get; set; }
    }
}
