//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopBranchInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public string ShopBranchName { get; set; }
        public int AddressId { get; set; }
        public string AddressDetail { get; set; }
        public string ContactUser { get; set; }
        public string ContactPhone { get; set; }
        public Himall.CommonModel.ShopBranchStatus Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string AddressPath { get; set; }
        public Nullable<int> ServeRadius { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<float> Latitude { get; set; }
        public string ShopImages { get; set; }
    }
}
