//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCategoryInfo:BaseModel
    {
        public ShopCategoryInfo()
        {
            this.ProductShopCategoryInfo = new HashSet<ProductShopCategoryInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public long ParentCategoryId { get; set; }
        public string Name { get; set; }
        public long DisplaySequence { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<ProductShopCategoryInfo> ProductShopCategoryInfo { get; set; }
    }
}
