//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopWithDrawInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ShopId { get; set; }
        public string CashNo { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public Himall.CommonModel.WithdrawStaus Status { get; set; }
        public Himall.CommonModel.WithdrawType CashType { get; set; }
        public decimal CashAmount { get; set; }
        public string Account { get; set; }
        public string AccountName { get; set; }
        public long SellerId { get; set; }
        public string SellerName { get; set; }
        public Nullable<System.DateTime> DealTime { get; set; }
        public string ShopRemark { get; set; }
        public string PlatRemark { get; set; }
        public string ShopName { get; set; }
        public string SerialNo { get; set; }
    }
}
