//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInfo:BaseModel
    {
        public ShopInfo()
        {
            this.Himall_CashDeposit = new HashSet<CashDepositInfo>();
            this.Himall_Coupon = new HashSet<CouponInfo>();
            this.Himall_CouponRecord = new HashSet<CouponRecordInfo>();
            this.Himall_FlashSale = new HashSet<FlashSaleInfo>();
            this.Himall_FlashSale1 = new HashSet<FlashSaleInfo>();
            this.Himall_ProductBrokerage = new HashSet<ProductBrokerageInfo>();
            this.Himall_ProductComments = new HashSet<ProductCommentInfo>();
            this.Himall_Products = new HashSet<ProductInfo>();
            this.Himall_ReceivingAddressConfig = new HashSet<ReceivingAddressInfo>();
            this.Himall_ShopBonus = new HashSet<ShopBonusInfo>();
            this.Himall_ShopBrandApplys = new HashSet<ShopBrandApplysInfo>();
            this.Himall_ShopBrands = new HashSet<ShopBrandsInfo>();
            this.Himall_StatisticOrderComments = new HashSet<StatisticOrderCommentsInfo>();
            this.Himall_VShop = new HashSet<VShopInfo>();
            this.Himall_FavoriteShops = new HashSet<FavoriteShopInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long GradeId { get; set; }
        public string ShopName { get; set; }
        public string Logo { get; set; }
        public string SubDomains { get; set; }
        public string Theme { get; set; }
        public bool IsSelf { get; set; }
        public ShopInfo.ShopAuditStatus ShopStatus { get; set; }
        public string RefuseReason { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CompanyName { get; set; }
        public int CompanyRegionId { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public CompanyEmployeeCount CompanyEmployeeCount { get; set; }
        public decimal CompanyRegisteredCapital { get; set; }
        public string ContactsName { get; set; }
        public string ContactsPhone { get; set; }
        public string ContactsEmail { get; set; }
        public string BusinessLicenceNumber { get; set; }
        public string BusinessLicenceNumberPhoto { get; set; }
        public int BusinessLicenceRegionId { get; set; }
        public Nullable<System.DateTime> BusinessLicenceStart { get; set; }
        public Nullable<System.DateTime> BusinessLicenceEnd { get; set; }
        public string BusinessSphere { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationCodePhoto { get; set; }
        public string GeneralTaxpayerPhot { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public int BankRegionId { get; set; }
        public string BankPhoto { get; set; }
        public string TaxRegistrationCertificate { get; set; }
        public string TaxpayerId { get; set; }
        public string TaxRegistrationCertificatePhoto { get; set; }
        public string PayPhoto { get; set; }
        public string PayRemark { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string SenderPhone { get; set; }
        public decimal Freight { get; set; }
        public decimal FreeFreight { get; set; }
        public Nullable<Himall.Model.ShopInfo.ShopStage> Stage { get; set; }
        public Nullable<int> SenderRegionId { get; set; }
        public string BusinessLicenseCert { get; set; }
        public string ProductCert { get; set; }
        public string OtherCert { get; set; }
        public string legalPerson { get; set; }
        public Nullable<System.DateTime> CompanyFoundingDate { get; set; }
        public Nullable<Himall.CommonModel.ShopBusinessType> BusinessType { get; set; }
        public string IDCard { get; set; }
        public string IDCardUrl { get; set; }
        public string WeiXinNickName { get; set; }
        public Nullable<int> WeiXinSex { get; set; }
        public string WeiXinAddress { get; set; }
        public string WeiXinTrueName { get; set; }
        public string WeiXinOpenId { get; set; }
        public Nullable<bool> AutoAllotOrder { get; set; }
        public string WeiXinImg { get; set; }
        public string IDCardUrl2 { get; set; }
    
        public virtual ICollection<CashDepositInfo> Himall_CashDeposit { get; set; }
        public virtual ICollection<CouponInfo> Himall_Coupon { get; set; }
        public virtual ICollection<CouponRecordInfo> Himall_CouponRecord { get; set; }
        public virtual ICollection<FlashSaleInfo> Himall_FlashSale { get; set; }
        public virtual ICollection<FlashSaleInfo> Himall_FlashSale1 { get; set; }
        public virtual ICollection<ProductBrokerageInfo> Himall_ProductBrokerage { get; set; }
        public virtual ICollection<ProductCommentInfo> Himall_ProductComments { get; set; }
        public virtual ICollection<ProductInfo> Himall_Products { get; set; }
        public virtual ICollection<ReceivingAddressInfo> Himall_ReceivingAddressConfig { get; set; }
        public virtual ICollection<ShopBonusInfo> Himall_ShopBonus { get; set; }
        public virtual ICollection<ShopBrandApplysInfo> Himall_ShopBrandApplys { get; set; }
        public virtual ICollection<ShopBrandsInfo> Himall_ShopBrands { get; set; }
        public virtual ICollection<StatisticOrderCommentsInfo> Himall_StatisticOrderComments { get; set; }
        public virtual ICollection<VShopInfo> Himall_VShop { get; set; }
        public virtual ICollection<FavoriteShopInfo> Himall_FavoriteShops { get; set; }
    }
}
