//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationValueInfo:BaseModel
    {
        public SpecificationValueInfo()
        {
            this.SellerSpecificationValueInfo = new HashSet<SellerSpecificationValueInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public SpecificationType Specification { get; set; }
        public long TypeId { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<SellerSpecificationValueInfo> SellerSpecificationValueInfo { get; set; }
        public virtual ProductTypeInfo TypeInfo { get; set; }
    }
}
