//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeInfo:BaseModel
    {
        public long ThemeId { get; set; }
        public Himall.CommonModel.ThemeType TypeId { get; set; }
        public string MainColor { get; set; }
        public string SecondaryColor { get; set; }
        public string WritingColor { get; set; }
        public string FrameColor { get; set; }
        public string ClassifiedsColor { get; set; }
    }
}
