//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VShopInfo:BaseModel
    {
        public VShopInfo()
        {
            this.VShopExtendInfo = new HashSet<VShopExtendInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string Name { get; set; }
        public long ShopId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int VisitNum { get; set; }
        public int buyNum { get; set; }
        public VShopInfo.VshopStates State { get; set; }
        private string logo { get; set; }
        private string backgroundImage { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string HomePageTitle { get; set; }
        public string WXLogo { get; set; }
    
        public virtual ICollection<VShopExtendInfo> VShopExtendInfo { get; set; }
        public virtual ShopInfo Himall_Shops { get; set; }
    }
}
