//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeiActivityInfo:BaseModel
    {
        public WeiActivityInfo()
        {
            this.Himall_WeiActivityAward = new HashSet<WeiActivityAwardInfo>();
            this.Himall_WeiActivityWinInfo = new HashSet<WeiActivityWinInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string ActivityTitle { get; set; }
        public Himall.CommonModel.WeiActivityType ActivityType { get; set; }
        public string ActivityDetails { get; set; }
        public string ActivityUrl { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Himall.CommonModel.WeiParticipateType ParticipationType { get; set; }
        public Nullable<int> ParticipationCount { get; set; }
        public int ConsumePoint { get; set; }
        public string CodeUrl { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual ICollection<WeiActivityAwardInfo> Himall_WeiActivityAward { get; set; }
        public virtual ICollection<WeiActivityWinInfo> Himall_WeiActivityWinInfo { get; set; }
    }
}
