//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeiActivityAwardInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public long ActivityId { get; set; }
        public int AwardLevel { get; set; }
        public Himall.CommonModel.WeiActivityAwardType AwardType { get; set; }
        public int AwardCount { get; set; }
        public float Proportion { get; set; }
        public Nullable<int> Integral { get; set; }
        public Nullable<long> BonusId { get; set; }
        public Nullable<long> CouponId { get; set; }
    
        public virtual WeiActivityInfo Himall_WeiActivityInfo { get; set; }
    }
}
