//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXCardLogInfo:BaseModel
    {
        public WXCardLogInfo()
        {
            this.Himall_WXCardCodeLog = new HashSet<WXCardCodeLogInfo>();
        }
    
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public string CardId { get; set; }
        public string CardTitle { get; set; }
        public string CardSubTitle { get; set; }
        public string CardColor { get; set; }
        public Nullable<int> AuditStatus { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public Nullable<WXCardLogInfo.CouponTypeEnum> CouponType { get; set; }
        public Nullable<long> CouponId { get; set; }
    
        public virtual ICollection<WXCardCodeLogInfo> Himall_WXCardCodeLog { get; set; }
    }
}
