//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXCardCodeLogInfo:BaseModel
    {
        long _id;
        public new long Id { get{ return _id; } set{ _id=value; base.Id = value; } }
        public Nullable<long> CardLogId { get; set; }
        public string CardId { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public int CodeStatus { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public Nullable<WXCardLogInfo.CouponTypeEnum> CouponType { get; set; }
        public Nullable<long> CouponCodeId { get; set; }
        public string OpenId { get; set; }
    
        public virtual WXCardLogInfo Himall_WXCardLog { get; set; }
    }
}
